#! /bin/bash

# Si aucun argument n'est donné, applique sur les fichiers du dossier courant
if (($# == 0))
then
    FILES="$(ls)"
else
    FILES="$@"
fi

# Suppression des retours chariot
for FILE in $(ls)
do
    if [[ -f $FILE ]]
    then
	[[ ! -w $FILE ]] && echo "Fichier $FILE non modifiable."
	sed -i 's/\r//g' "$FILE"
    fi
done
